spring:
  application:
    name: usage-service

  # Kafka Consumer
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_URL}
    consumer:
      group-id: usage-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: energyUsageEvent:org.zr.kafka.event.EnergyUsageEvent

    # Kafka Producer
    template:
      default-topic: energy-alerts
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# InfluxDB Configuration
influx:
  url: ${INFLUX_DB_URL}
  token: ${INFLUX_DB_TOKEN}
  org: ${INFLUX_DB_ORG}
  bucket: ${INFLUX_DB_BUCKET}

device:
  service:
    url: ${DEVICE_SERVICE_URL}
user:
  service:
    url: ${USER_SERVICE_URL}

server:
  port: 8083